improve design
SURYAKANTSHARMA/CountryPicker pull request #86
Opened 2022-02-01 13:12 UTC by SURYAKANTSHARMA

2022-02-01 16:47 UTC, Sharkesm requested changes

2022-02-01 16:47 UTC, Sharkesm commented on Example/TestCountryPickerFramework/ViewController.swift
Optional: May as well capture the variables instead 

```
{ [countryImageView, countryCodeButton] country in
       countryImageView.isHidden = false
       countryImageView.image = country.flag
       countryCodeButton.setTitle(country.dialingCode, for: .normal)
}
```

2022-02-01 16:48 UTC, Sharkesm requested changes
Also, the example project is corrupted. I can't seem to compile the app. Can you have a look into it, thanks

2022-02-02 07:13 UTC, SURYAKANTSHARMA commented on CountryPicker/CountryPicker/CountryPickerController.swift
>      }
didn't get you ? in lazy var we are constructing searchController and here we are setting navigationItem's property Or can you suggest code for better

2022-02-02 08:19 UTC, SURYAKANTSHARMA commented
> thanks

sure between whats the issue it is working for me. Can you try `pod install`

2022-02-07 11:33 UTC, merged